<div class="container-fluid">
    <h1 class="text-dark text-center" style="margin-top: 20vh;"> Adicionar Categoria </h1>
    <form action="<?= route('subcategories.create') ?>" method="POST" class="<?= $subcategory->hasErrors() ? '' : 'was-validated' ?>" novalidate>
        <div class="form-container">
            <span class="form-message">Campos marcados com asterísco são obrigatórios. (*)</span>

            <div class="row">
                <div class="col-12">
                    <label for="name">
                        <p>Nome *</p>
                        <input
                            formControlName="name"
                            type="text"
                            name="subcategory[name]"
                            id="name"
                            required
                            minlength="3"
                            value="<?= $subcategory->name ?>"
                            autocomplete="given-name"
                        >
                    </label>
                    <input type="hidden" name="subcategory[category_id]" value="<?= $categoryId ?>">
                </div>
            </div>

            <div class="row">
                <div class="col-6">
                    <div class="clear defaultButton">
                        <button type="reset">Limpar</button>
                    </div>
                </div>
                <div class="col-6">
                    <div class="submitButton defaultButton">
                        <button type="submit" class="btn btn-primary">Adicionar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>