<div class="container-fluid">
    <div class="row form-group">
        <div class="col-12 col-xl-4 col-lg-4">
            <input
            type="text"
            class="form-control"
            placeholder="PESQUISAR"
            />
        </div>
        <div class="col-6 col-xl-2 col-lg-2 d-flex justify-content-center">
        </div>
        <div class="col-12 col-lg-6 col-xl-6 d-flex justify-content-end">
            <div class="btn search">
                <a class="d-flex align-items-center justify-content-center" href="<?= route('users.new') ?>">
                    <i class="fa-solid fa-plus"></i>
                    <span class="text-center fs-3"> Nova Empresa</span>
                </a>
            </div>
        </div>
    </div>
    <div class="companycontent">
        <div class="row">
            <div class="col-12">
                <table class="table" style="color: black">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th class="d-none d-md-table-cell">E-mail</th>
                        <th class="d-none d-md-table-cell">Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($users as $user) : ?>
                        <tr>
                            <td><a href="<?= route('users.show', ['id' => $user->id]) ?>">#<?= htmlspecialchars($user->id, ENT_QUOTES, 'UTF-8') ?></a></td>
                            <td><?= htmlspecialchars($user->name, ENT_QUOTES, 'UTF-8') ?></td>
                            <td class="d-none d-md-table-cell"><?= htmlspecialchars($user->email, ENT_QUOTES, 'UTF-8') ?></td>
                            <td class="d-none d-md-table-cell"><?= htmlspecialchars($user->role, ENT_QUOTES, 'UTF-8') ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>