<div class="main-section">
    <div class="title-section">
        <h1 class="title">
            Treinamento Interno Para Escritórios de Contabilidade
        </h1>
        <p class="title-description">
            Acesse vídeos de treinamento, acompanhe o calendário fiscal e mantenha-se atualizado com as melhores práticas contábeis.
        </p>
    </div>

    <div class="main-buttons">
        <button class="mainButton" id="mainButtonOne">Explorar Vídeos</button>
        <button class="mainButton" id="mainButtonTwo">Ver Agenda Fiscal</button>
    </div>
</div>