<div class="container-fluid">
    <form action="<?= route('tutorials.create') ?>" method="POST" class="<?= $tutorial->hasErrors() ? '' : 'was-validated' ?>" novalidate>
        <div class="form-container">
            <span class="form-message">Campos marcados com asterísco são obrigatórios. (*)</span>

            <div class="row">
                <div class="col-12">
                    <label for="title">
                        <p>Nome *</p>
                        <input
                            formControlName="title"
                            type="text"
                            name="tutorial[title]"
                            id="name"
                            required
                            minlength="3"
                            value="<?= $tutorial->title ?>"
                            autocomplete="given-name"
                        >
                    </label>
                    <input type="hidden" name="tutorial[subcategory_id]" value="<?= $subcategoryId ?>">
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <label for="description">
                        <p>Descrição do Vídeo *</p>
                        <input
                            formControlName="description"
                            type="text"
                            name="tutorial[description]"
                            id="description"
                            required
                            minlength="5"
                            value="<?= $tutorial->description ?>"
                            autocomplete="given-name"
                        >
                    </label>
                    <div class="invalid-feedback"><?= $tutorial->errors('title') ? $tutorial->errors('title') : '' ?></div>
                </div>
            </div>

            <div class="row">
                <div class="col-6">
                    <label for="link">
                        <p>Link do Vídeo *</p>
                        <input
                            formControlName="link"
                            type="text"
                            name="tutorial[link]"
                            id="link"
                            required
                            minlength="5"
                            value="<?= $tutorial->link ?>"
                        >
                    </label>
                </div>        
                <div class="col-6">
                    <label for="recorded_at">
                    <p>Data de Gravação *</p>
                    <input
                        formControlName="recorded_at"
                        type="date"
                        name="tutorial[recorded_at]"
                        id="recorded_at"
                        required
                        minlength="5"
                    >
                    </label>   
                </div>   
            </div>

            <div class="row">
                <div class="col-12">
                    <label class="text-dark fw-bold" for="status">Adicionar Tags</label>
                    <select class="form-select" name="tutorial[tags][]" id="status" multiple data-multi-select>
                        <?php foreach ($tags as $tag) : ?> 
                            <option value="<?= $tag->id ?>"><?= $tag->name ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            

            <div class="row">
                <div class="col-6">
                    <div class="clear defaultButton">
                        <button type="reset">Limpar</button>
                    </div>
                </div>
                <div class="col-6">
                    <div class="submitButton defaultButton">
                        <button type="submit" class="btn btn-primary">Adicionar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>