<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12 d-flex justify-content-center text-dark">
            <h1><?= $tutorial->title ?></h1> 
        </div>
    </div>

    <div class="row">
        <div class="col-12 d-flex justify-content-center text-dark">
            <p><?= $tutorial->description ?></p>
        </div>
    </div>

    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <iframe 
                src="<?= $tutorial->link ?>" 
                title="YouTube video player" 
                frameborder="0" 
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                allowfullscreen
                style="width: 50%; height: 50vh">
            </iframe>
        </div>
    </div>

    <div class="row">
        <div class="col-12 d-flex justify-content-center text-dark">
            <?php if (!empty($tags)): ?>
                <?php foreach ($tags as $tag): ?>
                    <div class="border d-flex justify-content-around align-items-center" style="width: 10vh; margin-right: 20px; border-radius: 20px; background-color: #d1d1d1">
                        <?= $tag->name ?>
                        <i class="fa-solid fa-x cursor-pointer" onclick="event.preventDefault(); document.getElementById('delete-form-<?= $tag->id ?>').submit();"></i>
                        <form id="delete-form-<?= $tag->id ?>" action="<?= route('tags.destroy') ?>" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="id" value="<?= $tag->id ?>">
                            <input type="hidden" name="tutorial_id" value="<?= $tutorial->id ?>">
                        </form>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
            <p>Este tutorial não possui tags associadas.</p>
            <?php endif; ?>
        </div>  
    </div>
</div>