<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
    <link rel="stylesheet" href="/assets/css/application.css">
    <link rel="stylesheet" href="/assets/css/home/home.css">
    <link rel="stylesheet" href="/assets/css/list.css">
    <link rel="stylesheet" href="/assets/css/newUser.css">
    <link rel="stylesheet" href="/assets/css/tutorials/index.css">
    <link rel="stylesheet" href="/assets/css/tutorials/new.css" type="text/css">
    <link rel="stylesheet" href="/assets/css/subcategories/subcategories.css">
    <link rel="stylesheet" href="/assets/css/profile/profile.css">
</head>
<body style="background-color: #ffffff; color: white;">
    <header>
        <nav class="header-nav">
            <div class="begin">            
                <i class="fa-solid fa-house"></i>
                <a href="#" class="header-a">Início</a>
            </div>
            <ul class="header-ul">
                <li class="header-item">
                    <a href="" class="header-a">Tutoriais</a>
                </li>
                <li class="header-item">
                    <a href="" class="header-a">Empresas</a>
                </li>
                <li class="header-item">
                    <a href="" class="header-a">Agenda Tributária</a>
                </li>
                <li class="header-item">
                    <a href="" class="header-a"><i class="fa-regular fa-user"></i></a>
                </li>
            </ul>
        </nav>
    </header>
    <?php require '_flash_message.phtml'; ?>
    <?php require $view ?>
       


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/15c8bda6b4.js" crossorigin="anonymous"></script>
    <script src="/assets/js/tagSelection.js"></script>
    <script src="/assets/js/application.js"></script>
</body>
</html>
