<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="/assets/css/login.css">
  </head>
  <body class="min-h-screen bg-gray-50 flex flex-col">
      <?php require '_flash_message.phtml'; ?>
      <?php require $view ?>

      <script src="https://cdn.tailwindcss.com"></script>
  </body>
</html>
